### ISSUE TITLE
Error in plotting logic

### ISSUE THREAD

**Issue by cvbriggler** [AtriumAI/MarketingBot#1]
In the app, enter the following prompt: "Show me the top 10 campaigns with the best conversion rates."

Here is a copy of the traceback:
"File ""C:\Users\cv.briggler_atrium\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py"", line 534, in _run_script
    exec(code, module.__dict__)
File ""C:\Users\cv.briggler_atrium\Documents\Repos\MarketingBot\src\toggle.py"", line 419, in <module>
    df['MONTH-YEAR'] = df['MONTH'].astype(str) + '-' + df['YEAR'].astype(str)
                       ~~^^^^^^^^^
File ""C:\Users\cv.briggler_atrium\anaconda3\Lib\site-packages\pandas\core\frame.py"", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
File ""C:\Users\cv.briggler_atrium\anaconda3\Lib\site-packages\pandas\core\indexes\base.py"", line 3655, in get_loc
    raise KeyError(key) from err"

**Comment by cvbriggler** [comment]
There is an if-then-elsif for handling how to configure a figure object for plotly. The logic in the conditional is not correctly handling the likely data set structure coming from common prompts. In this case, it is expecting MONTH and YEAR columns which are not in the result set.

**Comment by mtwomey** [comment]
@cvbriggler This should be fixed on main now. Kindly confirm. Note, I've merged my branched to main.

**Comment by cvbriggler** [comment]
Looks good!
